# Generated by Django 6.1 on 2026-08-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New chat', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('dialect', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL / MariaDB'), ('mssql', 'SQL Server'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('oracle', 'Oracle'), ('redshift', 'Amazon Redshift'), ('trino', 'Trino / Presto'), ('clickhouse', 'ClickHouse'), ('duckdb', 'DuckDB'), ('databricks', 'Databricks')], default='postgres', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('db_user', models.CharField(blank=True, max_length=120)),
                ('password_enc', models.TextField(blank=True)),
                ('db_name', models.CharField(blank=True, max_length=120)),
                ('db_url', models.CharField(blank=True, help_text='Full SQLAlchemy URL for warehouses. Overrides host/port/user/password.', max_length=500)),
                ('collection_name', models.SlugField(help_text='Vector store collection. One per database.', max_length=80, unique=True)),
                ('index_status', models.CharField(choices=[('none', 'Not indexed'), ('indexing', 'Indexing…'), ('ready', 'Ready'), ('error', 'Error')], default='none', max_length=12)),
                ('index_error', models.TextField(blank=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_vectors', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='chat.databaseprofile'),
        ),
        migrations.CreateModel(
            name='LLMProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_url', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=160)),
                ('api_key_enc', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=0.1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='llm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='chat.llmprofile'),
        ),
    ]
