# Generated by Django 6.1 on 2026-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('en', 'English'), ('fa', 'فارسی (Persian)'), ('ar', 'العربية (Arabic)'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('tr', 'Türkçe'), ('zh', '中文'), ('ru', 'Русский')], default='auto', max_length=8),
        ),
    ]
