# Generated by Django 6.1 on 2026-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_queryexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='auto_clarify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
