# Generated by Django 6.1 on 2026-08-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_auto_clarify_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_databases', models.BooleanField(default=False)),
                ('can_edit_llms', models.BooleanField(default=False)),
                ('databases', models.ManyToManyField(blank=True, related_name='db_access_grants', to='chat.databaseprofile')),
                ('llms', models.ManyToManyField(blank=True, related_name='llm_access_grants', to='chat.llmprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
