# Generated by Django 6.1 on 2026-08-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_useraccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='databases',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='llms',
        ),
    ]
