# Generated by Django 6.1 on 2026-08-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_useraccess_databases_remove_useraccess_llms'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseprofile',
            name='icrl_avg_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='databaseprofile',
            name='icrl_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='databaseprofile',
            name='icrl_coverage_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='databaseprofile',
            name='icrl_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
